# number = int(input("구구단을 출력할 숫자를 입력하세요 : "))
s_number = int(input("출력할 구구단의 숫자를 입력하세요 : "))
print(f"{s_number}단")
#print(number,"단")
#print(number+"단")
#print(number+"단, "+ number+"단,"+ number+"단")
#print(f"{number}단,{number}단,{number}단" )
number = int(s_number)
result = number * 4
print(f"{result}")